### ISSUE TITLE
Nearby item detail fragment

### ISSUE THREAD

**Issue by henrijaeger** [WeFridge/WeFridge#23]

**Comment by PassiDel** [comment]
what is the difference to #14? I implemented the detail fragment from Figma in 524d08f4625aca9aeb087ee3585452a0c4a9f3cc, which will be merged with #32

**Comment by henrijaeger** [comment]
#14 might have been more related to the nearby items displayed as _rows_ of a list.
This explains why #14 depended on #11.
When the detail fragment for nearby items is ready, we can close this issue.

**Comment by frcroth** [comment]
Yes, I also can't see what this issue is about now
