### ISSUE TITLE
Refactor EditFragment

### ISSUE THREAD

**Issue by henrijaeger** [WeFridge/WeFridge#41]
- [x] refactor functions to activate/deactivate the LocationPicker ('activateLocationPickerElements' / 'deactivateLocationPickerElements'
- [x] modularize code in EditFragment, so that the file becomes smaller
- [x] consider to encapsulate the verification the contact email attribute into a seperate function (not null, not blank, not empty)
- [x] consider to encapsulate the verification of both isShared and location into a seperate function (location shall not be null, if isShared is set to true)
- [x] Add ability to reset the best by date
- [x] make Unit dropdown arrow clickable
- [x] remove usages of synthetic package

**Comment by PassiDel** [comment]
Bug: when the "locate me" button gets pressed and the fragment is changed, the callback will fail because it got destroyed

**Comment by henrijaeger** [comment]
> Bug: when the "locate me" button gets pressed and the fragment is changed, the callback will fail because it got destroyed

I would suggest moving this to another issue because this case may not occur too often.
