### ISSUE TITLE
Rework/Refactor Controllers

### ISSUE THREAD

**Issue by PassiDel** [WeFridge/WeFridge#48]
- [x] Move ModelList to class
- [x] create RecyclerView in onViewCreated (instead of async)
- [x] Replace OwnerController with UserController
  - [x] add getOwner
  - [x] add participants methods (from c54bd326b3273762e38a2e4d81127f5b003cce3f)
  - [x] move mail/name from SP to controller
- [x] Move ParticipantItem to seperate Class
- [x] Refactor SettingsFragment to use UserController
- [x] Move LocationServices to seperate Class (reusability)

**Comment by henrijaeger** [comment]
Closed by #66.
